apiVersion: apps/v1
kind: Deployment
metadata:
  name: activej-qr-alb-deployment
  labels:
    app: activej-qr-alb

spec:
  replicas: 33
  selector:
    matchLabels:
      app: activej-qr-alb
  template:
    metadata:
      labels:
        app: activej-qr-alb
    spec:
      containers:
        - name: activej-qr-alb-deployment
          image: 856329486021.dkr.ecr.us-east-1.amazonaws.com/activej-qr:v002x
          ports:
            - containerPort: 8080
          env:
            # Define the environment variable
            - name: MYSQL_DB_HOST # Notice that the case is different here
              # from the key name in the ConfigMap.
              valueFrom:
                configMapKeyRef:
                  name: activej-qr-alb-config           # The ConfigMap this value comes from.
                  key: MYSQL_DB_HOST # The key to fetch.
            - name: MYSQL_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: activej-qr-alb-config
                  key: MYSQL_DB_USER
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: activej-qr-alb-config
                  key: MYSQL_DB_PASSWORD
            - name: MYSQL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: activej-qr-alb-config
                  key: MYSQL_DB_PORT
          resources:
            requests:
              cpu: 400m
            limits:
              cpu: 2000m

