apiVersion: apps/v1
kind: Deployment
metadata:
  name: activej-p4-nlb-deployment
  labels:
    app: activej-p4-nlb

spec:
  replicas: 60
  selector:
    matchLabels:
      app: activej-p4-nlb
  template:
    metadata:
      labels:
        app: activej-p4-nlb
    spec:
      containers:
        - name: activej-p4-nlb-deployment
          image: 856329486021.dkr.ecr.us-east-1.amazonaws.com/activej-p4:v001x
          ports:
            - containerPort: 8080
          env:
            # Define the environment variable
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: activej-p4-nlb-config
                  key: USER
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: activej-p4-nlb-config
                  key: PASSWORD
            - name: ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: activej-p4-nlb-config
                  key: ADDRESS
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: activej-p4-nlb-config
                  key: DB_NAME

          resources:
            requests:
              cpu: 300m
            limits:
              cpu: 2000m

