apiVersion: apps/v1
kind: Deployment
metadata:
  name: activej-twitter-nlb-deployment
  labels:
    app: activej-twitter-nlb

spec:
  replicas: 30
  selector:
    matchLabels:
      app: activej-twitter-nlb
  template:
    metadata:
      labels:
        app: activej-twitter-nlb
    spec:
      containers:
        - name: activej-twitter-nlb-deployment
          image: 856329486021.dkr.ecr.us-east-1.amazonaws.com/activej-twitter:v001x
          ports:
            - containerPort: 8080
          env:
            # Define the environment variable
            - name: ZK_ADDR
              valueFrom:
                configMapKeyRef:
                  name: activej-twitter-nlb-config
                  key: ZK_ADDR
          resources:
            requests:
              cpu: 400m
            limits:
              cpu: 1000m

